permalink: /:year/:month/:day/:title.html
markdown: kramdown 
pygments: true
filter: 'category'


kramdown:
  input: GFM

# 作者信息
author: 
  name: triompha
  email: triompha@163.com
  link: http://blog.triompha.com
  weibo: ""
  github: http://github.com/triompha

# 站点信息
title: triompha的博客 
description: triompha的博客
url: http://blog.triompha.com
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: https://avatars3.githubusercontent.com/u/1892355?v=3&s=460
#favicon:https://avatars3.githubusercontent.com/u/1892355?v=3&s=460
 
# google analytics 设置
#ga:
#  id: UA-54767140-1
#  url: yansu.org

# disqus 设置
#disqus:
#  shortname: triompha
